{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-grafana.fullname" . }}-config
  namespace: {{ include "monitoring-grafana.namespace" . }}
  labels:
    {{- include "monitoring-grafana.labels" . | nindent 4 }}

data:
  grafana.ini: |
    {{- range $section, $values := .Values.grafana.config }}
    [{{ $section }}]
    {{- range $key, $value := $values }}

    {{- if and (eq $section "auth.generic_oauth") (eq $key "role_attribute_path") }}
    role_attribute_path = {{- range $.Values.grafana.accessGroups.admin.users }} metadata.name == '{{ . }}' && 'Admin' ||{{- end }}{{- range $.Values.grafana.accessGroups.viewer.users }} metadata.name == '{{ . }}' && 'Viewer' ||{{- end }} 'None'
    {{- else }}
    {{ $key }} = {{ $value }}
    {{- end }}

    {{- end }}
    {{- end }}
{{- end }}
