{{- if .Values.oauthProxy.enabled }}
- name: oauth-proxy
  image: "{{ .Values.oauthProxy.image.repository }}:{{ .Values.oauthProxy.image.tag }}"
  imagePullPolicy: {{ .Values.oauthProxy.image.pullPolicy }}
  ports:
    - name: oauth-proxy
      containerPort: {{ .Values.oauthProxy.port }}
      protocol: TCP
  args:
    - --provider=openshift
    - --https-address=:{{ .Values.oauthProxy.port }}
    - --http-address=
    - --email-domain=*
    - --upstream=http://localhost:3000
    - --openshift-service-account={{ include "monitoring-grafana.serviceAccountName" . }}
    - --pass-user-headers=true
    - --pass-access-token=true
    - --cookie-secret-file=/etc/proxy/secrets/session_secret
  volumeMounts:
    - name: oauth-proxy-secret
      mountPath: /etc/proxy/secrets
      readOnly: true
{{- end }}
