{{- if and .Values.grafana.enabled .Values.oauthProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-grafana.fullname" . }}-oauth-proxy
  namespace: {{ include "monitoring-grafana.namespace" . }}
  labels:
    {{- include "monitoring-grafana.labels" . | nindent 4 }}
type: Opaque
data:
  session_secret: {{ required "oauthProxy.cookieSecret is required when oauthProxy.enabled=true" .Values.oauthProxy.cookieSecret | b64enc | quote }}
{{- end }}
